### ISSUE TITLE
Gradient and Hessian Calculation 

### ISSUE THREAD

**Issue by Harshtherocking** [Harshtherocking/Optimization-IMA-314#10]
More of a DOUBT rather than an issue.
To calculate **Gradient** or **Hessian** matrix, do we write function already providing these values like 
```python
lambda x : np.array([2*x[0], 2*x[1]])
```
 or we find them out using **Difference equation**

**Comment by Ankur7891** [comment]
Yeah, we do make functions since the Loss function is always known beforhand for the Optimization.
